
## generate a batch of training data from 'data' generated by fakearray

from showit import image
import matplotlib.pyplot as plot
import numpy as np
from fakearray import calcium_imaging

from neurocatcher import dataTrain

data,series,truth=calcium_imaging(shape=(512,512), n=300, t=10, withparams=True)

data=data*255/data.max()
data=np.transpose(data,(1,2,0))

data=np.expand_dims(data,0)

batchData,batchTruth=dataTrain(data,[truth],10,120,120-36,0,255,upDown=0,rotate=0)

for i,pic in enumerate(batchData):
	image(np.mean(pic,axis=2))
	plot.show()
	image(batchTruth[i,:,:,0])
	plot.show()